{"name": "登录成功", "status": "passed", "description": "测试登录模块", "parameters": [{"name": "case", "value": "[2, '正确的手机号、错误的密码，登录失败', '13715297700', 12345678, 'y', None, '用户名或密码错误']"}], "start": 1721380543563, "stop": 1721380546112, "uuid": "9f79e6af-72c9-4c7f-9d7d-3d8268e3e107", "historyId": "f5f17384023a65d5d866556153cfc5e2", "testCaseId": "ca3777cc8a7dff9e1a878161527364cd", "fullName": "test_case.test_testin_login.TestLogin#test_login_ddt", "labels": [{"name": "feature", "value": "login-test"}, {"name": "epic", "value": "项目hkc"}, {"name": "tag", "value": "run(order=1)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('env')"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_testin_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "hkc0208725"}, {"name": "thread", "value": "17172-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_testin_login"}]}