{"name": "登录成功", "status": "passed", "description": "测试登录模块", "parameters": [{"name": "case", "value": "[2, '正确的手机号、错误的密码，登录失败', '13715297719', 12345678, 'y', None, '用户名或密码错误']"}], "start": 1714468575608, "stop": 1714468580573, "uuid": "64016e7d-730d-4f65-bf01-ae67cba43991", "historyId": "f3c567fdc29f169e4fcc9f069da86d07", "testCaseId": "ca3777cc8a7dff9e1a878161527364cd", "fullName": "test_case.test_testin_login.TestLogin#test_login_ddt", "labels": [{"name": "epic", "value": "项目hkc"}, {"name": "feature", "value": "login-test"}, {"name": "tag", "value": "run(order=1)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('env')"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_testin_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "hkc0208725"}, {"name": "thread", "value": "33580-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_testin_login"}]}