{"uuid": "54aa0199-1367-4667-947f-eb892609e4bc", "children": ["465ac91a-786b-4853-bd54-f8ef8c00b2ad"], "befores": [{"name": "generate_one_program", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: File not found : D:\\\\ui\\\\data\\\\test001.jpeg\n  (Session info: chrome=118.0.5993.118)\nStacktrace:\n\tGetHandleVerifier [0x00007FF7846A78A2+54818]\n\t(No symbol) [0x00007FF784616AD2]\n\t(No symbol) [0x00007FF7844CDA3B]\n\t(No symbol) [0x00007FF7845082EC]\n\t(No symbol) [0x00007FF78452EAAA]\n\t(No symbol) [0x00007FF784505036]\n\t(No symbol) [0x00007FF78452ECC0]\n\t(No symbol) [0x00007FF7845475A2]\n\t(No symbol) [0x00007FF78452E883]\n\t(No symbol) [0x00007FF784503691]\n\t(No symbol) [0x00007FF7845048D4]\n\tGetHandleVerifier [0x00007FF784A0B9A2+3610402]\n\tGetHandleVerifier [0x00007FF784A61870+3962352]\n\tGetHandleVerifier [0x00007FF784A59D5F+3930847]\n\tGetHandleVerifier [0x00007FF784743656+693206]\n\t(No symbol) [0x00007FF784621638]\n\t(No symbol) [0x00007FF78461D944]\n\t(No symbol) [0x00007FF78461DA72]\n\t(No symbol) [0x00007FF78460E123]\n\tBaseThreadInitThunk [0x00007FFF5C2B257D+29]\n\tRtlUserThreadStart [0x00007FFF5CCCAA48+40]\n\n", "trace": "  File \"D:\\sw_install\\python-install\\lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\_pytest\\fixtures.py\", line 909, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\git\\ui_test\\test_case\\test_play_bill.py\", line 134, in generate_one_program\n    mediapage.upload_media()\n  File \"D:\\git\\ui_test\\pageobject\\media_page.py\", line 51, in upload_media\n    self.upload_media_file(filepath)\n  File \"D:\\git\\ui_test\\pageobject\\media_page.py\", line 132, in upload_media_file\n    up_load_ele.send_keys(filepath)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 231, in send_keys\n    self._execute(\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 395, in _execute\n    return self._parent.execute(command, params)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 348, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "点击上传按钮", "status": "passed", "start": 1718846215022, "stop": 1718846215630}, {"name": "进行文件上传", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: File not found : D:\\\\ui\\\\data\\\\test001.jpeg\n  (Session info: chrome=118.0.5993.118)\nStacktrace:\n\tGetHandleVerifier [0x00007FF7846A78A2+54818]\n\t(No symbol) [0x00007FF784616AD2]\n\t(No symbol) [0x00007FF7844CDA3B]\n\t(No symbol) [0x00007FF7845082EC]\n\t(No symbol) [0x00007FF78452EAAA]\n\t(No symbol) [0x00007FF784505036]\n\t(No symbol) [0x00007FF78452ECC0]\n\t(No symbol) [0x00007FF7845475A2]\n\t(No symbol) [0x00007FF78452E883]\n\t(No symbol) [0x00007FF784503691]\n\t(No symbol) [0x00007FF7845048D4]\n\tGetHandleVerifier [0x00007FF784A0B9A2+3610402]\n\tGetHandleVerifier [0x00007FF784A61870+3962352]\n\tGetHandleVerifier [0x00007FF784A59D5F+3930847]\n\tGetHandleVerifier [0x00007FF784743656+693206]\n\t(No symbol) [0x00007FF784621638]\n\t(No symbol) [0x00007FF78461D944]\n\t(No symbol) [0x00007FF78461DA72]\n\t(No symbol) [0x00007FF78460E123]\n\tBaseThreadInitThunk [0x00007FFF5C2B257D+29]\n\tRtlUserThreadStart [0x00007FFF5CCCAA48+40]\n\n", "trace": "  File \"D:\\git\\ui_test\\pageobject\\media_page.py\", line 51, in upload_media\n    self.upload_media_file(filepath)\n  File \"D:\\git\\ui_test\\pageobject\\media_page.py\", line 132, in upload_media_file\n    up_load_ele.send_keys(filepath)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 231, in send_keys\n    self._execute(\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 395, in _execute\n    return self._parent.execute(command, params)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 348, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\sw_install\\python-install\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1718846215630, "stop": 1718846217691}], "start": 1718846213731, "stop": 1718846217825}], "start": 1718846213731, "stop": 1718846218063}