{"name": "登录成功", "status": "passed", "description": "测试登录模块", "parameters": [{"name": "case", "value": "[6, '错误的账号、正确的密码，登录失败', 'uitest123', 'Aa12345678', 'y', None, '用户名或密码错误']"}], "start": 1721807444013, "stop": 1721807445943, "uuid": "71f09894-88ce-4b8b-8cd0-c6f413c7a274", "historyId": "f76895ae537446d964295b4a1f553767", "testCaseId": "ca3777cc8a7dff9e1a878161527364cd", "fullName": "test_case.test_testin_login.TestLogin#test_login_ddt", "labels": [{"name": "epic", "value": "项目hkc"}, {"name": "feature", "value": "login-test"}, {"name": "tag", "value": "run(order=1)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('env')"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_testin_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "hkc0208725"}, {"name": "thread", "value": "2268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_testin_login"}]}